//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.27 at 01:50:43 PM CEST 
//


package de.uulm.cyv17.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for alu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="alu">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wordSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="inputsOperandA" type="{}inputList"/>
 *         &lt;element name="inputsOperandB" type="{}inputList"/>
 *         &lt;element name="output1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="output2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="operations" type="{}operationList"/>
 *         &lt;element name="conditions" type="{}conditionList" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="control" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "alu", propOrder = {

})
public class Alu {

    @XmlElement(required = true)
    protected String id;
    protected int wordSize;
    @XmlElement(required = true)
    protected InputList inputsOperandA;
    @XmlElement(required = true)
    protected InputList inputsOperandB;
    @XmlElement(required = true)
    protected String output1;
    @XmlElement(required = true)
    protected String output2;
    @XmlElement(required = true)
    protected OperationList operations;
    protected ConditionList conditions;
    protected String status;
    @XmlElement(required = true)
    protected String control;
    @XmlAttribute(name = "x")
    protected Integer x;
    @XmlAttribute(name = "y")
    protected Integer y;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the wordSize property.
     * 
     */
    public int getWordSize() {
        return wordSize;
    }

    /**
     * Sets the value of the wordSize property.
     * 
     */
    public void setWordSize(int value) {
        this.wordSize = value;
    }

    /**
     * Gets the value of the inputsOperandA property.
     * 
     * @return
     *     possible object is
     *     {@link InputList }
     *     
     */
    public InputList getInputsOperandA() {
        return inputsOperandA;
    }

    /**
     * Sets the value of the inputsOperandA property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputList }
     *     
     */
    public void setInputsOperandA(InputList value) {
        this.inputsOperandA = value;
    }

    /**
     * Gets the value of the inputsOperandB property.
     * 
     * @return
     *     possible object is
     *     {@link InputList }
     *     
     */
    public InputList getInputsOperandB() {
        return inputsOperandB;
    }

    /**
     * Sets the value of the inputsOperandB property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputList }
     *     
     */
    public void setInputsOperandB(InputList value) {
        this.inputsOperandB = value;
    }

    /**
     * Gets the value of the output1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutput1() {
        return output1;
    }

    /**
     * Sets the value of the output1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutput1(String value) {
        this.output1 = value;
    }

    /**
     * Gets the value of the output2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutput2() {
        return output2;
    }

    /**
     * Sets the value of the output2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutput2(String value) {
        this.output2 = value;
    }

    /**
     * Gets the value of the operations property.
     * 
     * @return
     *     possible object is
     *     {@link OperationList }
     *     
     */
    public OperationList getOperations() {
        return operations;
    }

    /**
     * Sets the value of the operations property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationList }
     *     
     */
    public void setOperations(OperationList value) {
        this.operations = value;
    }

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionList }
     *     
     */
    public ConditionList getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionList }
     *     
     */
    public void setConditions(ConditionList value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the control property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControl() {
        return control;
    }

    /**
     * Sets the value of the control property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControl(String value) {
        this.control = value;
    }

    /**
     * Gets the value of the x property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setX(Integer value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setY(Integer value) {
        this.y = value;
    }

}
