//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.27 at 01:50:43 PM CEST 
//


package de.uulm.cyv17.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for custom complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="custom">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="generics" type="{}genericsList" minOccurs="0"/>
 *         &lt;element name="connectors" type="{}customConnectorsList"/>
 *         &lt;element name="definition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "custom", propOrder = {

})
public class Custom {

    @XmlElement(required = true)
    protected String id;
    protected GenericsList generics;
    @XmlElement(required = true)
    protected CustomConnectorsList connectors;
    @XmlElement(required = true)
    protected String definition;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the generics property.
     * 
     * @return
     *     possible object is
     *     {@link GenericsList }
     *     
     */
    public GenericsList getGenerics() {
        return generics;
    }

    /**
     * Sets the value of the generics property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericsList }
     *     
     */
    public void setGenerics(GenericsList value) {
        this.generics = value;
    }

    /**
     * Gets the value of the connectors property.
     * 
     * @return
     *     possible object is
     *     {@link CustomConnectorsList }
     *     
     */
    public CustomConnectorsList getConnectors() {
        return connectors;
    }

    /**
     * Sets the value of the connectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomConnectorsList }
     *     
     */
    public void setConnectors(CustomConnectorsList value) {
        this.connectors = value;
    }

    /**
     * Gets the value of the definition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefinition(String value) {
        this.definition = value;
    }

}
